version: "2"
services:
  graze-postgres:
    image: "postgres:9.6-alpine"

    container_name: graze-postgres
    volumes:
      - graze-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=graze
      - POSTGRES_USER=graze

  graze-api:
    build: ./api
    container_name: graze-api
    environment:
      - DB_SERVER=graze-postgres
    ports:
      - 9001:9000
    links:
      - graze-postgres

  graze-ui:
    build: ./client
    container_name: graze-ui
    ports:
      - 5000:5000
    links:
      - graze-api

volumes:
  graze-data:
